import type { Metadata } from "next";

import "./globals.css";

import Dashboard from "./pages/Dashboard";
import Subject from "./pages/Subject";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Dashboard/>
        {/* <Subject/> */}
        {children}
      </body>
    </html>
  );
}
